# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-podid
  namespace: ns-csitest
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: crt-csiname
    type: kubernetes.io/tls
    data: 
    - objectName: crt-csiname
      key: crt-csiname.key
    - objectName: crt-csiname
      key: crt-csiname.crt  
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: akv-csi533             # Set to the name of your key vault
#    cloudName: "azure"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: crt-csiname
          objectType: cert              # object types: secret, key, or cert
    tenantId: b41b72d0-4e9f-4c26-8a69-f949f367c91d                # The tenant ID of the key vault